### ISSUE TITLE
Add Button component

### ISSUE THREAD

**Issue by nbkhope** [nenkan/ui#1]
Create a Button component that uses the classes defined in https://github.com/nenkan/css/blob/master/button.scss

Keep it simple. For this issue, just reproduce the examples from https://nenkan.github.io/css/#button

The prop for the Button variant should be "modifier. For example:

```
<Button modifier="danger">Button Danger Text</Button>
```

You should also allow additional class names to be passed in via className prop:

```
<Button className="more classes here">
```

**Comment by developer-irfan** [comment]
@nbkhope assign me this task i will create button component

**Comment by nbkhope** [comment]
@developer-irfan I just saw this. Since you were the first to comment, I will assign you.

**Comment by nbkhope** [comment]
@Niravprajapati1 you commented second, but I created another simple issue if you would like to help out: https://github.com/nenkan/ui/issues/2. Let me know.

**Comment by nbkhope** [comment]
`@developer-irfan`, unassigning you since I haven't heard from you.

**Comment by alvarotorrestx** [comment]
I'd like to try this as well, since I do see this is still open, let me know. 😊

**Comment by nbkhope** [comment]
@alvarotorrestx thanks, I assigned you to it. So only you will work on this issue.

For now it's sufficient to just have the three cases:

primary, secondary, danger

So we'd use like this:

``` 
<Button modifier="primary">

<Button modifier="danger">

<Button modifier="secondary">
```

The approach is simply adding the corresponding class to the class names of the component. You can leverage https://www.npmjs.com/package/classnames that is already installed.

example:
```
classNames('button', { 'button--primary': props.modifier === 'primary'
```

**Comment by alvarotorrestx** [comment]
Thanks, I'll get started asap

**Comment by nbkhope** [comment]
Resolved by https://github.com/nenkan/ui/commit/f113246e1ac297360734ab54b9049b5545cb6b11
