### ISSUE TITLE
Pass through props given to Button

### ISSUE THREAD

**Issue by nbkhope** [nenkan/ui#105]
Right now when I use the Button component like

```
<Button onClick={someFunction}>Click me</Button>
```

The onClick prop doesnt get passed to the underlying `<button>` component.

We must ensure all props passed to Button are passed down to lowercase button as well.

```
<button {...props}
```

**Comment by alvarotorrestx** [comment]
Hey there, can I help with issue? I want to try and contribute to your project.

**Comment by nbkhope** [comment]
@alvarotorrestx  oops, sorry I had to unassign you because looks like @aditya-raj2230 submitted a pull request first. I'll take that.

@alvarotorrestx there will be future opportunities for this. I think the button will need some modifiers to add classes for primary, danger, etc. I'll let you know.
