### ISSUE TITLE
Rename Breadcrumb.js to breadcrumb.js

### ISSUE THREAD

**Issue by nbkhope** [nenkan/ui#19]
Adopt lowercase naming convention for the file for breadcrumb component.

Make sure to update import statements for breadcrumb if they exist.

https://github.com/nenkan/ui/blob/139e74f4259fa996240087c66d8cd998cae4488a/index.js#L1

**Comment by nbkhope** [comment]
@Auguxtow do you want to tackle this one?

**Comment by Auguxtow** [comment]
I can do it
