### ISSUE TITLE
Add Table component

### ISSUE THREAD

**Issue by nbkhope** [nenkan/ui#2]
Create a Table component that should be used like this:

```
<Table>
  <thead>...</thead>
  <tbody>...</tbody>
</Table>
```

All you have to do is make a component named Table that applies the [className "table" from @nenkan/css](https://nenkan.github.io/css/#table) and renders whatever children is passed.

You should also allow additional class names to be passed in via className prop:

```
<Table className="more classes here">
```

**Comment by Niravprajapati1** [comment]
Can i solve this issue

**Comment by Niravprajapati1** [comment]
Done a pr !

**Comment by nbkhope** [comment]
@Niravprajapati1 yes. You can clone the repository, make a branch off master. You can look at the other files for examples how to build a component. I can help you if you don't understand how. Once complete, submit a pull request and I will review.

**Comment by nbkhope** [comment]
@Niravprajapati1 to close this issue, we still need to have the Table component accept a prop called `className`. Right now it doesn't:

https://github.com/nenkan/ui/blob/139e74f4259fa996240087c66d8cd998cae4488a/Table.js#L7

For example, one solution:

```
import classNames from 'classnames';

// ...

<table className={classNames('table', props.className)}>
```
