### ISSUE TITLE
Adopt lower-case-with-hyphen file naming convention

### ISSUE THREAD

**Issue by nbkhope** [nenkan/ui#7]
Rename all files so they adhere to naming convention:

- all letters lowercase
- words separated by a hyphen `-`

For example:

Breadcrumb.js -> breadcrumb.js

MarkdownRegion.js -> markdown-region.js

- [x] #19
- [x] #20
- [x] https://github.com/nenkan/ui/issues/21

**Comment by Niravprajapati1** [comment]
Can you assign this issue to me?

**Comment by nbkhope** [comment]
@Niravprajapati1 this issue aggregates multiple subtasks. How about you do https://github.com/nenkan/ui/issues/19 ?

**Comment by Niravprajapati1** [comment]
Sure 😃
